version: "3.8"

services:
  db:
    image: 'postgres:16'
    container_name: scholarhaven-db
    environment:
      POSTGRES_DB: ${DB_NAME:-scholarhaven}
      POSTGRES_USER: ${DB_USERNAME:-zunaied}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-zunaied}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: